apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- application.yaml
configurations:
- params.yaml
configMapGenerator:
- name: ci-pipeline-parameters
  behavior: merge
  env: params.env
generatorOptions:
 disableNameSuffixHash: true
vars:
- name: generateName
  objref:
    kind: ConfigMap
    name: ci-pipeline-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.generateName
commonLabels:
  app.kubernetes.io/name: ci-pipeline
  app.kubernetes.io/instance: $(generateName)
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: kubeflow
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.6
