apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: application
spec:
  componentKinds:
  - group: apps
    kind: Deployment
  - group: core
    kind: Service
  - group: core
    kind: ServiceAccount
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  assemblyPhase: "Pending"
  descriptor:
    type: "kubeflow"
