apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs: 
  - list
- apiGroups:
  - kubeflow.org
  resources:
  - profiles
  verbs: 
  - create
