apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: $(generateName)
spec:
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cpu
              operator: In
              values:
              - skylake
              - cascadelake
#    nodeSelector:
#      accelerator: $(accelerator_type)
