apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: operator
spec:
    spec:
      containers:
      - command:
        - /opt/kubeflow/tf-operator.v1beta2
        - --alsologtostderr
        - -v=1
        - --enable-gang-scheduling
