apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- workflows.yaml
namespace: kubeflow-test-infra
configMapGenerator:
- name: kfctl-workflows-parameters
  env: params.env
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: kfctl-workflows-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
configurations:
- params.yaml
