apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run-model
spec:
  inputs:
    params:
    - name: imageName
      type: string
      description: container image name
    - name: acceleratorName
      type: string
      description: accelerator name
    - name: acceleratorCount
      type: string
      description: accelerator count
  steps:
  - name: run-model
    #image: ${inputs.params.imageName}
    image: gcr.io/constant-cubist-173123/tf-test-gpu@sha256:706ff9468ba09eab305c2768321a9950e6e5c1be9e0ccfd8bc9af9e4ea6becee
    resources:
      limits:
        #${inputs.params.acceleratorName}: "${inputs.params.acceleratorCount}"
        nvidia.com/gpu: '1'
    volumeMounts:
    - name: kubeflow
      mountPath: /kubeflow
  volumes:
  - name: kubeflow
    persistentVolumeClaim:
      claimName: ci-pipeline-run-persistent-volume-claim
