apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run-model
spec:
#  inputs:
#    params:
#    - name: imageName
#      type: string
#      description: container image name
#    - name: acceleratorType
#      type: string
#      description: accelerator type
#    - name: acceleratorCount
#      type: string
#      description: accelerator count
  steps:
  - name: run-model
#    image: ${inputs.params.imageName}
    image: "gcr.io/constant-cubist-173123/tf-test-skx:355316a"
    resources:
      limits:
        #${inputs.params.acceleratorType}: ${inputs.params.acceleratorCount}
        cpu: 1
    volumeMounts:
    - name: kubeflow
      mountPath: /kubeflow
  volumes:
  - name: kubeflow
    persistentVolumeClaim:
      claimName: ci-pipeline-run-persistent-volume-claim
