apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run-model
spec:
  inputs:
    params:
    - name: imageName
      type: string
      description: container image name
    - name: acceleratorName
      type: string
      description: accelerator name
    - name: acceleratorCount
      type: string
      description: accelerator count
  steps:
  - name: run-model
    #image: ${inputs.params.imageName}
    image: gcr.io/constant-cubist-173123/tf-test-gpu@sha256:1b0fd2ddb871c4cb56234ffa428c6661fa4024edf140bcbe7865aab49e7f5b70"
    command: ["/bin/sleep", "infinity"]
    #command: ["python", "model.py"]
    workingDir: /kubeflow
    resources:
      limits:
        #${inputs.params.acceleratorName}: "${inputs.params.acceleratorCount}"
        nvidia.com/gpu: '1'
