apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- config-map.yaml
- deployment.yaml
- mutating-webhook-configuration.yaml
- role-binding.yaml
- service-account.yaml
- service.yaml
- stateful-set.yaml
commonLabels:
  kustomize.component: admission-webhook
images:
  - name: gcr.io/kubeflow-images-public/admission-webhook
    newName: gcr.io/kubeflow-images-public/admission-webhook
    newTag: v20190419-v0-47-g08da905d-e3b0c4
  - name: gcr.io/kubeflow-images-public/ingress-setup
    newName: gcr.io/kubeflow-images-public/ingress-setup
    newTag: latest
