kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ci-pipeline-run-persistent-volume-claim
  namespace: $(namespace)
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
