apiVersion: v1
kind: ConfigMap
metadata:
  name: update-manifests-commands
data:
  rebuild-manifests.sh: |-
    #!/usr/bin/env bash
    pushd ../common/centraldashboard/base
    echo updating image in centraldashboard/kustomization.yaml
    kustomize edit set image gcr.io/kubeflow-images-public/centraldashboard=gcr.io/kubeflow-images-public/centraldashboard@$(cat /kubeflow/centraldashboard-digest)
    popd
    make generate
    make test
    if (( $? == 0 )); then
      #cat pr.json | jq '. |  .Head.Repo'
      #"https://github.com/kkasravi/kubeflow.git"
      #cat pr.json | jq .Head.Repo?
      #"https://github.com/kkasravi/kubeflow.git"
      #$ cat pr.json | jq .Head.Branch?
      #"e2e-pipelineruns"
      echo remote url is 
    fi
