apiVersion: v1
kind: ConfigMap
metadata:
  name: update-manifests-commands
data:
  rebuild-manifests.sh: |-
    #!/usr/bin/env bash
    pushd ../common/centraldashboard/base
    kustomize edit set image gcr.io/kubeflow-images-public/centraldashboard=gcr.io/kubeflow-images-public/centraldashboard@$(cat /kubeflow/centraldashboard-digest)
    popd
    make generate
    make test
