apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: update-manifests
spec:
  inputs:
    params:
    - name: containerImage
      type: string
      description: pod container image
    - name: imageName
      type: string
      description: pod container image
    - name: pathToManifestsDir
      type: string
      description: Where the components manifest dir is
      default: /workspace/manifests
    resources:
    - name: kubeflow
      type: git
    - name: manifests
      type: git
    - name: $(image_name)
      type: image
  steps:
  - name: update-manifests
    workingDir: "/workspace/$(inputs.resources.manifests.name)/$(inputs.params.pathToManifestsDir)"
    image: $(inputs.params.container_image)
    command: ["/bin/sleep", "infinity"]
    #command: ["/workspace/$(inputs.resources.kubeflow.name)/py/kubeflow/kubeflow/ci/rebuild-manifests.sh"]
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/gcp-credentials/key.json
    envFrom:
    - configMapRef:
        name: ci-pipeline-parameters
    volumeMounts:
    - name: gcp-credentials
      mountPath: /secret/gcp-credentials
    - name: kubeflow
      mountPath: /kubeflow
  volumes:
  - name: gcp-credentials
    secret:
      secretName: gcp-credentials
  - name: kubeflow
    persistentVolumeClaim:
      claimName: ci-pipeline-run-persistent-volume-claim
