apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: update-manifests
spec:
  inputs:
    resources:
    - name: manifests
      type: git
    - name: $(image_name)
      type: image
    - name: $(pull_request_repo)
      type: pullRequest
    params:
    - name: pathToManifestsTestsDir
      type: string
      description: Where manifests tests are generated and run
      default: /workspace/manifests/tests
    - name: container_image
      type: string
      description: pod container image
  outputs:
    resources:
    - name: manifests
      type: git
  steps:
  - name: update-manifests
    workingDir: "/workspace/${inputs.resources.manifests.name}/${inputs.params.pathToManifestsTestsDir}"
    image: ${inputs.params.container_image}
    command: ["/bin/sleep", "infinity"]
    #command: ["/bin/bash", "/update-manifests-commands/rebuild-manifests.sh"]
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/kaniko-secret.json
    volumeMounts:
    - name: kaniko-secret
      mountPath: /secret
    - name: kubeflow
      mountPath: /kubeflow
    - name: update-manifests-commands
      mountPath: /update-manifests-commands
  volumes:
  - name: kaniko-secret
    secret:
      secretName: kaniko-secret
  - name: update-manifests-commands
    configMap:
      name: update-manifests-commands
  - name: kubeflow
    persistentVolumeClaim:
      claimName: ci-pipeline-run-persistent-volume-claim
