apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: application-status
spec:
  inputs:
    params:
    - name: container_image
      type: string
      description: pod container image
    - name: applications
      type: array
      description: The applications
  steps:
  - name: application-status
    image: $(inputs.params.container_image)
    command: ["/bin/sleep", "infinity"]
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/gcp-credentials/key.json
    volumeMounts:
    - name: gcp-credentials
      mountPath: /secret/gcp-credentials
  volumes:
  - name: gcp-credentials
    secret:
      secretName: gcp-credentials
