apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-push
spec:
  inputs:
    resources:
    - name: kubeflow
      type: git
    params:
    - name: dockerTarget
      type: string
      description: docker target arg
    - name: imageName
      type: string
    - name: pathToContext
      type: string
      description: The build context used by Kaniko
    - name: pathToDockerfile
      type: string
      description: The path to the dockerfile to build
  outputs:
    resources:
    - name: $(image_name)
      type: image
      outputImageDir: /kubeflow
  steps:
  - name: build-push
    image: gcr.io/kaniko-project/executor:v0.11.0
    command:
    - /kaniko/executor
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/kaniko/kaniko-secret.json
    args:
    - "--dockerfile=/workspace/$(inputs.resources.kubeflow.name)/$(inputs.params.pathToDockerfile)"
    - "--destination=$(outputs.resources.$(inputs.params.imageName).url)"
    - "--context=/workspace/$(inputs.resources.kubeflow.name)/$(inputs.params.pathToContext)"
    - "--target=$(inputs.params.dockerTarget)"
    - "--digest-file=/kubeflow/$(inputs.params.imageName)-digest"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /secret/kaniko
    - name: kubeflow
      mountPath: /kubeflow
  volumes:
  - name: kaniko-secret
    secret:
      secretName: kaniko-secret
  - name: kubeflow
    persistentVolumeClaim:
      claimName: ci-pipeline-run-persistent-volume-claim
