apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set
spec:
  serviceName: service
  template:
    spec:
      containers:
      - name: manager
        command:
        - /go/src/github.com/kubernetes-sigs/application/manager
        image: gcr.io/$(project)/application-controller:latest
        imagePullPolicy: Always
        env:
        - name: project
          value: $(project)
      serviceAccountName: service-account
  volumeClaimTemplates: []
