apiVersion: v1
kind: ConfigMap
metadata:
  name: update-gcp-config
data:
  update-gcp-config.sh: |-
    #!/usr/bin/env bash
    sed 's/cpu-pool-initialNodeCount:.*$/cpu-pool-initialNodeCount: $(cpu-pool-initialNodeCount)/' cluster-kubeflow.yaml > o
    mv o cluster-kubeflow.yaml
    sed 's/cpu-pool-machine-type:.*$/cpu-pool-machine-type: $(cpu-pool-machine-type)/' cluster-kubeflow.yaml > o
    mv o cluster-kubeflow.yaml
    sed 's/cpu-pool-max-nodes:.*$/cpu-pool-max-nodes: $(cpu-pool-max-nodes)/' cluster-kubeflow.yaml > o
    mv o cluster-kubeflow.yaml
    sed 's/cpu-pool-min-nodes:.*$/cpu-pool-min-nodes: $(cpu-pool-min-nodes)/' cluster-kubeflow.yaml > o
    mv o cluster-kubeflow.yaml
    sed 's/cpu-pool-min-cpu-platform:.*$/cpu-pool-min-cpu-platform: "$(cpu-pool-min-cpu-platform)"/' cluster-kubeflow.yaml > o
    mv o cluster-kubeflow.yaml
    sed '19 a \    cpu-pool-image-type: $(cpu-pool-image-type)' cluster-kubeflow.yaml > o
    mv o cluster-kubeflow.yaml
    sed 's/gpu-pool-initialNodeCount:.*$/gpu-pool-initialNodeCount: $(gpu-pool-initialNodeCount)/' cluster-kubeflow.yaml > o
    mv o cluster-kubeflow.yaml
    sed 's/gpu-pool-machine-type:.*$/gpu-pool-machine-type: $(gpu-pool-machine-type)/' cluster-kubeflow.yaml > o
    mv o cluster-kubeflow.yaml
    sed 's/gpu-pool-max-nodes:.*$/gpu-pool-max-nodes: $(gpu-pool-max-nodes)/' cluster-kubeflow.yaml > o
    mv o cluster-kubeflow.yaml
    sed 's/gpu-pool-min-nodes:.*$/gpu-pool-min-nodes: $(gpu-pool-min-nodes)/' cluster-kubeflow.yaml > o
    mv o cluster-kubeflow.yaml
    sed 's/gpu-type:.*$/gpu-type: $(gpu-type)/' cluster-kubeflow.yaml > o
    mv o cluster-kubeflow.yaml
    sed '29 a \    gpu-pool-image-type: $(gpu-pool-image-type)' cluster-kubeflow.yaml > o
    mv o cluster-kubeflow.yaml
    sed "125 a \          imageType: {{ properties['cpu-pool-image-type'] }}" cluster.jinja > o
    mv o cluster.jinja
    sed "165 a \        imageType: {{ properties['gpu-pool-image-type'] }}" cluster.jinja > o
    mv o cluster.jinja
