varReference:
- path: spec/params/value
  kind: Pipeline
- path: spec/tasks/params/value
  kind: Pipeline
- path: spec/resources/name
  kind: Pipeline
- path: spec/steps/image
  kind: Task
- path: spec/steps/volumeMounts/mountPath
  kind: Task
- path: spec/steps/workingDir
  kind: Task
