apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: notebook-controller
spec:
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment
    - group: core
      kind: ServiceAccount
  descriptor: 
    type: notebook-controller
    version: v1alpha1
    description: Notebooks controller allows users to create a custom resource \"Notebook\" (jupyter notebook).
    icons:
    maintainers:
    - name: Lun-kai Hsu
      email: lunkai@google.com
    owners:
    - name: Lun-kai Hsu
      email: lunkai@gogle.com
    keywords:
     - jupyter
     - notebook
     - notebook-controller
     - jupyterhub  
    links:
    - description: About
      url: "https://github.com/kubeflow/kubeflow/tree/master/components/notebook-controller"
  addOwnerRef: true
