apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tf-job-operator
spec:
  template:
    spec:
      containers:
      - name: tf-job-operator
        resources:
          requests:
            intel.com/skylake: 1
          limits:
            intel.com/skylake: 1
