apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- node.yaml
patchesStrategicMerge:
- deployment.yaml
namespace: kubeflow
configMapGenerator:
- name: tf-job-operator-device-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: skylake01a
  objref:
    kind: ConfigMap
    name: tf-job-operator-device-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.skylake01a
- name: skylake02a
  objref:
    kind: ConfigMap
    name: tf-job-operator-device-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.skylake02a
patchesJson6902:
- target:
    version: v1
    kind: Node
    name: $(skylake01a)
  path: patch.yaml
- target:
    version: v1
    kind: Node
    name: $(skylake02a)
  path: patch.yaml
configurations:
- params.yaml
